name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        type: string
        required: true

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxtst-dev libxfixes-dev

      - run: npm install

      - run: npm run make

      - name: Download cloudflared
        shell: bash
        run: |
          case "$RUNNER_OS" in
            Windows)
              curl -L \
                "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" \
                -o cloudflared.exe
              ;;

            Linux)
              curl -L \
                "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64" \
                -o cloudflared
              ;;

            macOS)
              curl -L \
                "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-arm64.tgz" |
                tar -xz
              ;;
          esac

      - name: Add cloudflared
        run: |
          find out/make -type f | head -20
          APP_DIR=$(dirname "$(find out/make -type f \( -name '*.exe' -o -name 'os-in-browser' \) | head -1)")
          cp cloudflared* "$APP_DIR/"

      - name: Rename
        shell: bash
        run: |
          mv out/make/zip/*/*/*.zip \
            "${{ runner.os }}-${{ runner.arch }}.zip"

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: ${{ runner.os }}-${{ runner.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          path: releases
          merge-multiple: true

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            "v${{ inputs.version }}" \
            releases/*.zip \
            --title "v${{ inputs.version }}" \
            --generate-notes