name: Remote Desktop
run-name: ${{ inputs.os }}

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating system
        type: choice
        required: true
        default: windows-latest
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest

      username:
        description: Username
        type: string
        required: true

      password:
        description: Password
        type: string
        required: true

jobs:
  job:
    name: URL
    runs-on: ${{ inputs.os }}

    environment:
      name: ${{ github.run_id }}

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Run remote desktop
        env:
          PORT: 8080
          METRICS_URL: "localhost:8081"
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
          ZIP_NAME: ${{ runner.os }}-${{ runner.arch }}.zip
        run: |
          export USERNAME=$(jq -r '.inputs.username // ""' "$GITHUB_EVENT_PATH")
          echo "::add-mask::${USERNAME}"

          export PASSWORD=$(jq -r '.inputs.password // ""' "$GITHUB_EVENT_PATH")
          echo "::add-mask::${PASSWORD}"

          case "$RUNNER_OS" in
            Linux)
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends \
                icewm \
                xvfb \
                libx11-6 \
                libxtst6 \
                libxfixes3

              read -r DISPLAY_NUMBER < <(
                Xvfb \
                  -displayfd 1 \
                  -screen 0 1920x1080x24 \
                  +extension XTEST \
                  +extension XFIXES \
                  -nolisten tcp
              )

              export DISPLAY=":$DISPLAY_NUMBER"

              icewm-session &

              OS_IN_BROWSER=./os-in-browser
              CLOUDFLARED=./cloudflared

              ;;

            Windows)
              OS_IN_BROWSER=./os-in-browser.exe
              CLOUDFLARED=./cloudflared.exe

              ;;

            macOS)
              OS_IN_BROWSER=./os-in-browser.app/Contents/MacOS/os-in-browser
              CLOUDFLARED=./cloudflared

              ;;
          esac

          gh release download "$RELEASE_TAG" \
            --repo "$GITHUB_REPOSITORY" \
            --pattern "${ZIP_NAME}" \
          || gh release download "$RELEASE_TAG" \
            --repo "kingdudely/os-in-browser" \
            --pattern "${ZIP_NAME}"

          unzip -q "${ZIP_NAME}"

          "${CLOUDFLARED}" tunnel --metrics="${METRICS_URL}" --url "http://localhost:${PORT}"

          until JSON="$(curl -sS "${METRICS_URL}/quicktunnel")"; do # "$CLOUDFLARED" --metrics"${METRICS_URL} ready
            sleep 1
          done

          HOSTNAME="$(jq -r '.hostname' <<< "${JSON}")"
          TUNNEL_URL="https://${HOSTNAME}"

          "${OS_IN_BROWSER}"