name: Remote Desktop
run-name: ${{ inputs.os }}

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating system
        type: choice
        required: true
        default: windows-latest
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest

      username:
        description: Username
        type: string
        required: true

      password:
        description: Password
        type: string
        required: true

jobs:
  job:
    name: URL
    runs-on: ${{ inputs.os }}

    environment:
      name: ${{ github.run_id }}

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Run remote desktop
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
          ZIP_NAME: ${{ runner.os }}-${{ runner.arch }}.zip
        run: |
          export USERNAME=$(jq -r '.inputs.username // ""' "$GITHUB_EVENT_PATH")
          echo "::add-mask::${USERNAME}"

          export PASSWORD=$(jq -r '.inputs.password // ""' "$GITHUB_EVENT_PATH")
          echo "::add-mask::${PASSWORD}"

          gh release download \
            --repo "$GITHUB_REPOSITORY" \
            --pattern "${ZIP_NAME}" \
          || gh release download \
            --repo "kingdudely/os-in-browser" \
            --pattern "${ZIP_NAME}"

          unzip -q "${ZIP_NAME}" || {
            status=$?
            if [ "$status" -ne 1 ]; then
              exit "$status"
            fi
          }
          case "$RUNNER_OS" in
            Linux)
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends \
                icewm \
                xvfb \
                libx11-6 \
                libxtst6 \
                libxfixes3

              read -r DISPLAY_NUMBER < <(
                Xvfb \
                  -displayfd 1 \
                  -screen 0 1920x1080x24 \
                  +extension XTEST \
                  +extension XFIXES \
                  -nolisten tcp
              )

              export DISPLAY=":$DISPLAY_NUMBER"

              icewm-session &

              ./os-in-browser

              ;;

            Windows)
              ./os-in-browser.exe

              ;;

            macOS)
              open ./os-in-browser.app

              ;;
          esac

          sleep 21600